import LeftSidebar from '@/components/LeftSidebar/LeftSidebar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex flex-col md:flex-row'>
          <aside className=''>
            <LeftSidebar />
          </aside>
          <section className='shrink w-full p-10'>{children}</section>
        </main>
      </body>
    </html>
  )
}
